### PR TITLE
Fix #111 and maybe minor fixes WIP

### LINKED ISSUE #111: PolyJuMP makes a feasible model infeasible
When using PolyJuMP, the following model is reported as infeasible.
```jl
using JuMP, PolyJuMP, Gurobi

m = Model(() -> PolyJuMP.QCQP.Optimizer(Gurobi.Optimizer()))

@variable m -1 <= jump_c[1:5] <= 1
@variable m -1 <= jump_s[1:5] <= 1

c = jump_c
s = jump_s

# Solutions:
#c = [0.91165750302348, 0.9436635072926446, 0.575952449978958, 0.624599296124994, 0.9896625334970969]
#s = [0.4109508452126525, 0.3309066106987665, 0.8174831957681062, 0.7809454009597355, -0.14341572365716249]

@constraint m c .^ 2 .+ s .^ 2 .== 1
@constraint m (((c[1]*c[2] - 0.4608811486294164c[3]*s[4] - 0.5700328131603017c[5]*s[3] - 0.6801846504873382s[3]*s[5]) + (0.5700328131603017* ((c[3]*c[4]) * s[5]))) + (-0.6801846504873382* ((c[3]*c[4]) * c[5]))) == 0
@constraint m (((-0.7382491921224805c[3]*s[4] - 0.17909626144720603c[5]*s[3] + 0.6503173528871414s[3]*s[5] + s[2]) + (0.17909626144720603* ((c[3]*c[4]) * s[5]))) + (0.6503173528871414* ((c[3]*c[4]) * c[5]))) == 0
@constraint m (((0.5700328131603017c[3]*c[5] + 0.6801846504873382c[3]*s[5] - 0.4608811486294164s[3]*s[4] + s[1]) + (0.5700328131603017* ((c[4]*s[3]) * s[5]))) + (-0.6801846504873382* ((c[4]*c[5]) * s[3]))) == 0
@constraint m (((0.8018647772886565c[3]*c[5] - 0.3382841731078751c[3]*s[5] + 0.49252075810927465s[3]*s[4] - c[1]) + (0.8018647772886565* ((c[4]*s[3]) * s[5]))) + (0.3382841731078751* ((c[4]*c[5]) * s[3]))) == 0
@constraint m (((0.17909626144720603c[3]*c[5] - 0.6503173528871414c[3]*s[5] - 0.7382491921224805s[3]*s[4]) + (0.17909626144720603* ((c[4]*s[3]) * s[5]))) + (0.6503173528871414* ((c[4]*c[5]) * s[3]))) == 0
@constraint m 0.6503173528871414c[5]*s[4] + 0.17909626144720603s[4]*s[5] - c[2] + 0.7382491921224805c[4] == 0

optimize!(m)
```
but the commented lines for `c` and `s` contain the solution. If you un-comment them, the model becomes feasible. (You can convince yourself otherwise. The infeasibility of roughly 1e-16 is due to rounding)

Sorry this is the most I could clean it up for today, I'll try harder tomorrow.

### PR DESCRIPTION
**Pull request by votroto**
Updating of polynomial variables throughout `final_touch` meant that polynomial and MOI variables were no longer in sync; this resulted in nonsensical models. 

My solution just updates the variables, then takes the sorting approach from `_scalar_polynomial` in `nl_to_polynomial.jl`. It is not great, but without more significant changes, some variable-order-preserving hocus-pocus will have to be done anyway.

I took the liberty of suggesting an edit for the `/` overload, which should now try to avoid creating rational polynomials.

The `_to_polynomial` for `ScalarQuadraticFunction` in `functions.jl` seems redundant after issue #110.

Tests that the variables are preserved should be written, but without more significant changes, that might be tricky. Maybe just a few e2e tests in the meantime? I will write a few for the `/`, at least.

Fixes #111

### CODE REVIEW

**Comment by votroto** [comment]
After more testing, this does not solve the issue.

**Comment by votroto** [comment]
Ah, it was wrong in the `_scalar_polynomial` already too.

File: src/nl_to_polynomial.jl [hunk 1]
```diff
@@ -94,7 +94,11 @@ function _to_polynomial!(
         return a^b
     elseif _is_operator(expr, :/) && length(operands) == 2
         a, b = _to_polynomial!.(Ref(d), T, operands)
-        return a / b
+        if iszero(MP.rem(a, b))
```
Comment (blegat) [inline src/nl_to_polynomial.jl:97]: You can call `Base.divrem` otherwise you computing it twice since both `div` and `rem` end up calling `divrem`

File: src/QCQP/MOI_wrapper.jl [hunk 2]
```diff
@@ -228,8 +228,14 @@ function _subs!(
         end
     end
     if !isempty(old_var)
+        to_old_map = Dict(zip(new_var, old_var))
```
Comment (blegat) [inline src/QCQP/MOI_wrapper.jl:231]: Good catch, can you add as comment that this is needed in case the order of `MP.variables(p.polynomial)` changes after substitution so we need to update the order in `p.variables` ?

**Comment by blegat** [comment]
The changes look good, thanks, just missing a few tests. Yes, unit tests calling the internal functions is good.

**Comment by blegat** [comment]
Need to fix format

File: src/QCQP/MOI_wrapper.jl [hunk 3]
```diff
@@ -211,6 +211,28 @@ function _subs!(
...
+    poly = MP.subs(p.polynomial, old => new)
+
+    all_new_vars = MP.variables(poly)
+    to_old_map = Dict(zip(new, old))
+    to_moi_map = Dict(zip(MP.variables(p.polynomial), p.variables))
+    moi_vars = [to_moi_map[get(to_old_map, v, v)] for v in all_new_vars]
+
+    return PolyJuMP.ScalarPolynomialFunction(poly, moi_vars)
+end
+
```
Comment (odow) [inline src/QCQP/MOI_wrapper.jl:234]:
```suggestion
```

File: src/nl_to_polynomial.jl [hunk 4]
```diff
@@ -109,7 +114,8 @@ function _to_polynomial(expr, ::Type{T}) where {T}
 end
 
 function _scalar_polynomial(d::Dict{K,V}, ::Type{T}, poly) where {T,K,V}
-    variable_map = collect(d)
+    var_set = Set(MP.variables(poly))
+    variable_map = Tuple{K, V}[(k, v) for (k, v) in d if v in var_set]
```
Comment (odow) [inline src/nl_to_polynomial.jl:118]:
```suggestion
    variable_map = Tuple{K,V}[(k, v) for (k, v) in d if v in var_set]
```

File: test/qcqp_extra.jl [hunk 5]
```diff
@@ -0,0 +1,174 @@
...
+# Random.seed! set below!
+
+function test_unconstrained_before_projection(T)
+    inner = Model{T}()
+    optimizer = MOI.Utilities.MockOptimizer(inner)
+    model = PolyJuMP.JuMP.GenericModel{T}(
+        () -> PolyJuMP.QCQP.Optimizer{T}(optimizer),
+    )
+    PolyJuMP.@variable(model, -1 <= a[1:2] <= 1)
+    PolyJuMP.@objective(model, Min, a[1]^2*a[2]^2)
```
Comment (odow) [inline test/qcqp_extra.jl:19]:
```suggestion
    PolyJuMP.@objective(model, Min, a[1]^2 * a[2]^2)
```

File: test/qcqp_extra.jl [hunk 6]
```diff
@@ -0,0 +1,174 @@
...
+    PolyJuMP.optimize!(model)
+
+    vis = MOI.get(inner, MOI.ListOfVariableIndices())
+    @test length(vis) == 4
+
```
Comment (odow) [inline test/qcqp_extra.jl:24]:
```suggestion
```

File: test/qcqp_extra.jl [hunk 7]
```diff
@@ -0,0 +1,174 @@
...
+end
+
+function test_unconstrained_after_projection(T)
+    inner = Model{T}()
+    optimizer = MOI.Utilities.MockOptimizer(inner)
+    model = PolyJuMP.JuMP.GenericModel{T}(
+        () -> PolyJuMP.QCQP.Optimizer{T}(optimizer),
+    )
+    PolyJuMP.@variable(model, -1 <= a <= 1)
+    PolyJuMP.@objective(model, Min, a^2)
```
Comment (odow) [inline test/qcqp_extra.jl:38]:
```suggestion
    PolyJuMP.@objective(model, Min, a^2)
```

File: test/qcqp_extra.jl [hunk 8]
```diff
@@ -0,0 +1,174 @@
...
+    model = PolyJuMP.JuMP.GenericModel{T}(
+        () -> PolyJuMP.QCQP.Optimizer{T}(optimizer),
+    )
+    PolyJuMP.@variable(model, -1 <= a <= 1)
+    PolyJuMP.@objective(model, Min, a^2)    
+    PolyJuMP.optimize!(model)
+
+    vis = MOI.get(inner, MOI.ListOfVariableIndices())
+    @test length(vis) == 1
+
```
Comment (odow) [inline test/qcqp_extra.jl:43]:
```suggestion
```

File: test/qcqp_extra.jl [hunk 9]
```diff
@@ -0,0 +1,174 @@
...
+function test_subs!_preserves_moi_sync(xs, ys, T)
+    p = _random_polynomial(xs, T)
+
+    mois = MOI.VariableIndex.(eachindex(xs))
+    vals = T.(randn(length(mois)))
+
+    mask = rand(Bool, length(xs))
+    is = Random.shuffle(eachindex(xs)[mask])
+    index = Dict{eltype(mois), eltype(xs)}(zip(mois[is], ys[is]))
```
Comment (odow) [inline test/qcqp_extra.jl:63]:
```suggestion
    index = Dict{eltype(mois),eltype(xs)}(zip(mois[is], ys[is]))
```

File: test/qcqp_extra.jl [hunk 10]
```diff
@@ -0,0 +1,174 @@
...
+end
+
+import TypedPolynomials
+@testset "TypedPolynomials" begin
+    TypedPolynomials.@polyvar(z[1:4])
+    TypedPolynomials.@polyvar(w[1:4])
+    types = [Float64, BigFloat, Rational{BigInt}]
+    samples = 10
+    TestQCQPExtra.run_tests_subs(z, w, samples, types)
+end
```
Comment (odow) [inline test/qcqp_extra.jl:174]:
```suggestion
end

```

**Comment by odow** [comment]
@blegat are the QCQP tests even run?

File: test/qcqp_extra.jl [hunk 11]
```diff
@@ -0,0 +1,165 @@
+module TestQCQPExtra
+
+using Test
+
+import MathOptInterface as MOI
+import MultivariatePolynomials as MP
+import PolyJuMP
+import Random
+
+
```
Comment (odow) [inline test/qcqp_extra.jl:10]:
```suggestion
```

**Comment by odow** [comment]
I've dropped the change to `a / b`. I'll re-add it in a separate PR.
