### PR TITLE
Fix _to_polynomial for ScalarAffineFunction and ScalarQuadraticFunction

### LINKED ISSUE #110: Unexpected expression type MathOptInterface.ScalarAffineFunction
Running
```jl
using JuMP, PolyJuMP, Gurobi
model = Model(() -> PolyJuMP.QCQP.Optimizer(Gurobi.Optimizer()))

@variable(model, 0 <= x <= 1)
@constraint(model, (0 + x) * (x * x) == 0)

optimize!(model)
```
results in
```
LoadError: PolyJuMP.InvalidNLExpression("Unexpected expression type `MathOptInterface.ScalarAffineFunction{Float64}` of `0.0 + 1.0 MOI.VariableIndex(1)`")
```

P.S. I am *so* sorry @blegat and thank you for your time on developing this package.

### PR DESCRIPTION
**Pull request by odow**
Closes #110

### CODE REVIEW

File: test/qcqp.jl [hunk 1]
```diff
@@ -199,6 +199,23 @@ function test_unbound_polynomial(x, y, T)
...
+    PolyJuMP.@expression(model, f, 0 + x)
+    PolyJuMP.@expression(model, g, x^2)
+    PolyJuMP.@constraint(model, f * g == 0)
+    PolyJuMP.optimize!(model)
+    F, S = ScalarQuadraticFunction{T}, EqualTo{T}
+    @test MOI.get(inner, MOI.NumberOfConstraints{F,S}()) == 2
+    @test MOI.get(inner, MOI.NumberOfVariables()) == 2
+    return
+end
+
```
Comment (odow) [inline test/qcqp.jl:217]:
```suggestion
```

**Comment by odow** [comment]
Codecov lies. This gets hit when I run locally?

**Review by blegat — APPROVED** [review]
